include ./tokyo-night-kitty.conf

# Font config
font_family     Liga SFMono  Nerd Font
italic_font     auto
bold_font       auto
font_size       10
placement_strategy top-left
adjust_line_height 6
adjust_column_width 0
hide_window_decorations no
disable_ligatures never

# Cursor
cursor_shape   block
cursor_blink_interval 0
cursor_stop_blink_after 15.0

# Window
remember_window_size   yes
initial_window_width   1300
initial_window_height  700
window_border_width 0
window_margin_width 0
window_padding_width 0
inactive_text_alpha 1.0
background_opacity 1

# Shell
close_on_child_death no
allow_remote_control yes
term xterm-256color

# Keys
clipboard_control write-clipboard write-primary no-append
map ctrl+shift+v        paste_from_clipboard
map ctrl+shift+s        paste_from_selection
map ctrl+shift+c        copy_to_clipboard
map shift+insert        paste_from_selection

map ctrl+equal    increase_font_size
map ctrl+minus    decrease_font_size
map ctrl+0 restore_font_size
